DATASET:
  TYPE: 'KITTI_eigen'
  PATH: '/dataset/kitti/data/'

DATA:
  MIN_DEPTH: 0.01
  MAX_DEPTH: 80.0
  NORMALIZE_MEAN: [0.485, 0.456, 0.406]
  NORMALIZE_STD: [0.229, 0.224, 0.225]
  CENTER_CROP_SIZE: [1216,352]
  TRAIN_CROP_SIZE: [320,320]
  OUTPUT_SIZE: [1216, 352]
  FX_Depth: 9.597910e+02
  FY_Depth: 9.569251e+02
  CX_Depth: 6.960217e+02
  CY_Depth: 2.241806e+02